version: '3.1'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "your_topic_name:1:1"
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - mynetwork

  nestjs-app:
    build:
      context: ./src/main.ts
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - mynetwork

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_PASSWORD: develop
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    networks:
      - mynetwork

networks:
  mynetwork:
